---
title: "Package Build and Test Enviroment Information"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

## Introduction

This document lists the R version and package vesions used in the development of
the pfsrsdk package. It is built automatically and reflects the latest
versions used. 

## Package Information

```{r comment=NA}
pd <- utils::packageDescription("pfsrsdk")
pd
```

## Build and Test Environment Information

```{r}
s <- utils::sessionInfo()
enviro <- as.data.frame(s$R.version)

knitr::kable(enviro[,1:5], format = "markdown")
knitr::kable(enviro[,6:10], format = "markdown")
knitr::kable(enviro[,11:length(enviro)], format = "markdown")
```

## Package Dependencies

```{r}
imports <- strsplit(utils::packageDescription("pfsrsdk")$Imports, "[[:punct:][:space:]]+")[[1]]
# TODO enable listing dependencies and their versions (RSDK-107)
importFrame <- data.frame(Package = imports)

knitr::kable(importFrame, format = "markdown", row.names = FALSE)
```

## Unit Test Results

```{r eval=FALSE}
#TODO re-enable block as part of output from running tests in CI (RSDK-108) 
log <- capture.output(tr <- testthat::test_dir("../tests/testthat"))

knitr::kable(as.data.frame(tr), longtable = TRUE, font_size = 7)
```
