---
title: "Package Build, Test Enviroment, and Dependencies Information"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

## Introduction

This document lists the R version and package vesions used in the development of
the pfsrsdk package. It is built automatically and reflects the latest
versions used. 

## Package Information

```{r comment=NA}
pd <- packageDescription("pfsrsdk")
pd
```

## Build and Test Environment Information

```{r}
s <- sessionInfo()
enviro <- as.data.frame(s$R.version)

knitr::kable(enviro[,1:5], format = "markdown")
knitr::kable(enviro[,6:10], format = "markdown")
knitr::kable(enviro[,11:length(enviro)], format = "markdown")
```

## Package Dependencies

```{r}
imports <- stringi::stri_remove_empty(strsplit(packageDescription("pfsrsdk", fields="Imports"), "[[:punct:][:space:]]+")[[1]])
versions <- sapply(imports, function(x) packageDescription(x, fields="Version"))
licenses <- sapply(imports, function(x) packageDescription(x, fields="License"))
urls <- sapply(imports, function(x) gsub("[,[:space:]]+", ", ", packageDescription(x, fields="URL")))
importFrame <- data.frame(Package = imports, Version = versions, License = licenses, URLs = urls)

knitr::kable(importFrame, format = "markdown", row.names = FALSE)
```

## Unit Test Results

```{r eval=FALSE}
#TODO re-enable block as part of output from running tests in CI (RSDK-108) 
log <- capture.output(tr <- testthat::test_dir("../tests/testthat"))

knitr::kable(as.data.frame(tr), longtable = TRUE, font_size = 7)
```
